version: '3'
# 
volumes:
  postgres_data:
      driver: local
# 
services:
  keycloak-db:
      image: postgres:16
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      command: start-dev
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_DB_PORT: 5432
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_PROXY: edge
      ports:
        - 80:8080
      depends_on:
        - keycloak-db

